models.py
from app import db
from datetime import datetime
import re

def slugify(s):
    pattern = r'[^\w+]'
    return re.sub(pattern, '-', s)


post_tags = db.Table('post_tags', db.Model.metadata,
                     db.Column('post_id', db.Integer, db.ForeignKey('post.id')),
                     db.Column('tag_id', db.Integer, db.ForeignKey('tag.id')),
                     )


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100))
    slug = db.Column(db.String(100), unique=True)
    body = db.Column(db.Text)
    created_at = db.Column(db.DateTime, default=datetime.now())

    tags = db.relationship('Tag', secondary=post_tags, backref=db.backref('posts', lazy='dynamic'))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.generate_slug()

    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title)

    def __repr__(self):
        return '<Post id: {}, title: {}>'.format(self.id, self.title)

class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    slug = db.Column(db.String(100), unique=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.slug = slugify(self.name)

    def __repr__(self):
        return '<Tag id: {}, name: {}>'.format(self.id, self.title)

posts/forms.py
from wtforms import Form, StringField, TextAreaField


class PostForm(Form):
    title = StringField('Title')
    body = TextAreaField('Body')

app.py
from flask import Flask
from config import Configuration
from flask_sqlalchemy import SQLAlchemy

from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager

app = Flask(__name__)
app.config.from_object(Configuration())
db = SQLAlchemy(app)

migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)

main.py
from app import app
import view
from app import db
from posts.blueprints import posts

app.register_blueprint(posts, url_prefix='/blog')

if __name__ == "__main__":
    app.run()

posts/blueprints.py
from flask import Blueprint
from flask import render_template
from models import Post, Tag

from flask import request
from posts.forms import PostForm
from flask import redirect

from app import db
from flask import url_for
posts = Blueprint('posts', __name__, template_folder='templates')


@posts.route('/create', methods=['POST', 'GET'])
def create_post():
    if request.method == "POST":
        title = request.form['title']
        body = request.form['body']

        post = Post(title=title, body=body)

        try:
            db.session.add(post)
            db.session.commit()
            return redirect(url_for('posts.index'))
        except:
            return "Error Method Create"
    form = PostForm()
    return render_template('posts/create_post.html', form=form)


@posts.route('/<slug>/edit/', methods=["POST", "GET"])
def edit_post(slug):
    post = Post.query.filter(Post.slug == slug).first_or_404()

    if request.method == "POST":
        form = PostForm(formdata=request.form, obj=post)
        form.populate_obj(post)
        db.session.commit()

        return redirect(url_for('posts.post_details', slug=post.slug))
    else:
        form = PostForm(obj=post)
        return render_template('posts/edit.html', post=post, form=form)


@posts.route('/')
def index():
    q = request.args.get('q')

    page = request.args.get('page')

    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    if q:
        posts = Post.query.filter(Post.title.contains(q) | Post.body.contains(q))
    else:
        posts = Post.query.order_by(Post.created_at.desc())

    pages = posts.paginate(page=page, per_page=5)
    return render_template('posts/index.html', posts=posts, pages=pages)


@posts.route('/<slug>')
def post_view(slug):
    post = Post.query.filter(Post.slug == slug).first()
    return render_template('posts/post.html', post=post)



@posts.route('/tag/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug == slug).first_or_404()
    posts = tag.posts.all()
    return render_template('posts/tag_detail.html', data=posts, tag=tag)

posts/templates/posts/create_post.html
{% extends 'base.html' %}

{%block content_title %}
<h1>Create a Post</h1>
{%endblock%}

{% block content %}
   <div class="container">
        <form action="{{ url_for('posts.create_post') }}" method="POST">
            {% for field in form %}
                <div class="form-group">
                    {{ field.label(class='control-label') }}
                    {{ field(class='form-control') }}
                </div>
            {% endfor %}
            <button class="btn btn-success" type="submit" role="button">Create</button>
        </form>
   </div>
{% endblock %}

posts/templates/posts/index.html
{% extends 'base.html' %}
{%block title %} Blueprint {%endblock%}

{%block content_title %}
Posts
{%endblock%}

{%block content %}

    <ul>
        {% for post in pages.items %}
        <li class="mt-2">
            <a href="{{url_for('posts.post_view', slug=post.slug)}}">  {{ post.title }} </a>
        </li>
        {% endfor %}
    </ul>
    <nav class="container-fluid">
      <ul class="pagination">
        <li class="page-item">
          <a class="page-link" href="./?page={{pages.prev_num}}" {% if not pages.has_prev %} style="display: none;" {% endif %}>
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>

        {% for page in pages.iter_pages() %}
            <li  {% if page == pages.page %} class="page-item active" {% else %} class="page-item" {% endif %}><a class="page-link" href="./?page={{page}}">{{page}}</a></li>
        {% endfor %}

        <li class="page-item">
          <a class="page-link" href="./?page={{pages.next_num}}" {% if not pages.has_next %} style="display: none;" {% endif %}>
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      </ul>
    </nav>

{%endblock%}

posts/templates/posts/post.html
{% extends 'base.html' %}
{%block title %} Blueprint {%endblock%}

{%block content_title %}
{{ post.title }}
{%endblock%}

{%block content %}
    <div class="tags">
        {% for tag in post.tags %}
        <span class="label label-primary"><a href="{{ url_for('posts.tag_detail', slug=tag.slug) }}">{{ tag.name }}</a></span>
        {% endfor %}
    </div>
    {{ post.body }}
{%endblock%}

posts/templates/posts/tag_detail.html
{% extends 'base.html' %}
{% block content %}
    <span><h3> Name of the tag: "{{ tag.name }}" .</h3></span>
    <div class="posts-container mt-4">
        {% for post in data %}
        <span><a href="{{ url_for('posts.post_view', slug=post.slug) }}">{{ post.title }}</a></span>
            <span>{{ post.body }}</span>
            <span>{{ post.id }}</span>
        {% endfor %}
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title%} {%endblock%} | Flask App</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{{ url_for('index')}}">BLOG</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{{url_for('posts.index')}}">Blueprints <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('posts.create_post')}}">Create Post</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" method="GET">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q" value="{{ request.args.get('q', '') }}" >
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
    <div class="container">
        <div class="row">
             <h1>{% block content_title %}
                 {%endblock%}
             </h1>
        </div>
             {% block content%}
                no content a
             {% endblock %}
    </div>
</body>
</html>